### PR TITLE
Game

### PR DESCRIPTION
**Pull request by DvdBerg**
Refactored the project by adding a Game class that now has some of the responsibilities of the Board class. This reduces the "god class level" of Board and transfers the current level and score to a more suitable class.

The methods processJewel() and processMatch() are moved to Game, along with the notifiers of the score and level. Some improvements can still be made, but I suggest we focus on the deadlines we have this week first.

### CODE REVIEW

**Comment by HugoKooijman** [comment]
Finally some much needed refactoring. I approve.

**Comment by BjornHo** [comment]
I took a look at it. Board is beginning to look better now. I do suggest removing some JavaDoc from some methods to get even better results. For example the JavaDoc above the method addBoardListener. It does not add more information at all.

**Comment by DvdBerg** [comment]
You are totally correct about the JavaDoc that needs to be removed. However, the Game branch wasn't really intended as a branch for refactoring/cleaning the project. It was only intended for the addition of the Game class. The refactoring that is done in this branch was purely to provide some functionality to the Game class (other than just the level and score). Other changes will need to be made to the Game/Board classes as well, but it is my suggestion to focus on this weeks sprint first. Besides, checking the JavaDoc is needed in almost all files of the project, so it should probably be done in a separate branch. Let me know if you agree with this, so we can determine whether we can merge or not.

**Comment by BjornHo** [comment]
Okay fair enough. We will focus on getting the requirements done first.

**Pull request merged**
